name: Linters and Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  install:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: yarn
  lint:
    needs: install
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
#      - uses: actions/checkout@v2
      - name: Run Linter
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: yarn test
  test:
    runs-on: ubuntu-latest
    needs:
      - install
      - lint

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
#      - uses: actions/checkout@v2
      - name: Run Tests
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: yarn lint
